---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	planner(planner)
	extractor(extractor)
	comps_retrieval(comps_retrieval)
	valuation_rent(valuation_rent)
	scenario_forecast(scenario_forecast)
	critic(critic)
	human_review(human_review)
	summarizer(summarizer)
	__end__([<p>__end__</p>]):::last
	__start__ --> planner;
	comps_retrieval --> valuation_rent;
	critic -.-> human_review;
	critic -.-> planner;
	critic -.-> summarizer;
	extractor --> comps_retrieval;
	human_review --> summarizer;
	planner -.-> comps_retrieval;
	planner -.-> extractor;
	scenario_forecast --> critic;
	valuation_rent --> scenario_forecast;
	summarizer --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
